import * as sanitizeHtml from 'sanitize-html';

export function sanitizeContent(content: string): string {
  return sanitizeHtml(content, {
    allowedTags: [
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'blockquote',
      'p',
      'a',
      'ul',
      'ol',
      'nl',
      'li',
      'b',
      'i',
      'strong',
      'em',
      'strike',
      'code',
      'hr',
      'br',
      'div',
      'table',
      'thead',
      'caption',
      'tbody',
      'tr',
      'th',
      'td',
      'pre',
      'img',
    ],
    allowedAttributes: {
      '*': ['style', 'class'],
      a: ['href', 'name', 'target'],
      img: ['src', 'alt', 'width', 'height', 'style'],
      table: ['border', 'cellpadding', 'cellspacing'],
    },
    allowedStyles: {
      '*': {
        color: [
          /^#(?:[0-9a-f]{3}){1,2}$/i,
          /^rgb\((\d{1,3}),(\d{1,3}),(\d{1,3})\)$/,
        ],
        'text-align': [/^left$/, /^right$/, /^center$/],
        'font-size': [/^\d+(?:px|em|%)$/],
        'font-weight': [/^bold$/, /^\d+$/],
        'font-style': [/^italic$/],
        'text-decoration': [/^underline$/],
        'background-color': [
          /^#(?:[0-9a-f]{3}){1,2}$/i,
          /^rgb\((\d{1,3}),(\d{1,3}),(\d{1,3})\)$/,
        ],
        'max-width': [/^\d+(?:px|%)$/],
        'max-height': [/^\d+(?:px|%)$/],
        width: [/^auto$/, /^\d+(?:px|%)$/],
        height: [/^auto$/, /^\d+(?:px|%)$/],
        margin: [/^\d+(?:px|%)?(\s+\d+(?:px|%)?){0,3}$/],
        'border-radius': [/^\d+(?:px|%)$/],
        display: [/^block$/, /^inline$/, /^inline-block$/],
      },
    },
    allowedSchemes: ['http', 'https', 'ftp', 'mailto', 'tel', 'data', 's3'],
    allowedSchemesByTag: {
      img: ['http', 'https', 'data', 's3'],
    },
    allowProtocolRelative: true,
  });
}
