export enum ActivityType {
  NOTE_CREATED = 'NOTE_CREATED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  NOTE_DELETED = 'NOTE_DELETED',
  NOTE_PINNED = 'NOTE_PINNED',
  NOTE_UNPINNED = 'NOTE_UNPINNED',
  NOTE_TASK_CREATED = 'NOTE_TASK_CREATED',
  NOTE_TASK_UPDATED = 'NOTE_TASK_UPDATED',
  NOTE_TASK_DELETED = 'NOTE_TASK_DELETED',
  NOTE_COMMENT_ADDED = 'NOTE_COMMENT_ADDED',
  NOTE_COMMENT_UPDATED = 'NOTE_COMMENT_UPDATED',
  NOTE_COMMENT_DELETED = 'NOTE_COMMENT_DELETED',
}
